# Generated by Django 5.2.9 on 2025-12-22 02:45

import invoicing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='buyer_hash',
            field=models.CharField(default=invoicing_app.models.generate_buyer_room_hash, max_length=16, unique=True),
        ),
    ]
