# Generated by Django 5.2.9 on 2025-12-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing_app', '0002_buyer_buyer_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
