# Generated by Django 5.2.9 on 2025-12-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing_app', '0003_seller_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='seller_hash',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
