# Generated by Django 5.2.9 on 2025-12-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing_app', '0004_room_seller_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='seller_hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
