# Generated by Django 5.2.9 on 2025-12-25 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing_app', '0006_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiItemNegotiationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Invoice Created'), ('edited_invoice', 'Invoice Edited'), ('edited_item', 'Invoice Item Edited'), ('added_item', 'Invoice Item Added'), ('removed_item', 'Invoice Item Removed'), ('approved', 'Buyer Approved'), ('disapproved', 'Buyer Disapproved'), ('paid', 'Buyer Marked as Paid'), ('confirmed', 'Seller Confirmed Payment')], max_length=50)),
                ('actor', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_item_history', to='invoicing_app.invoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multi_item_history', to='invoicing_app.invoiceitem')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_item_history', to='invoicing_app.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
